# version of the docker compose
version: '3.6'

#We can have many services for example db
services:
  web:
    #build the current directory
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8080 
    volumes:
      - .:/code
    ports:
      - 8080:8080

  elasticsearch:
    image: launcher.gcr.io/google/elasticsearch2
    ports:
      - "9200:9200" # for RESTFUL API
      - "9300:9300" # for node communication in case you run multiple instances