# version of the docker compose
version: '3.6'

#We can have many services for example db
services:
  web:
    #build the current directory
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8080 
    volumes:
      - .:/code
    ports:
      - 8080:8080

