all:
        hosts:
                test:
                        ansible_user: sam
                        # ansible_host: 104.197.137.136
                        # ansible_host: 34.67.53.206
                        ansible_host: muokipolls.duckdns.org
                        # ansible_host: 'www.muokipolls.duckdns.org'
                        # ansible_port: 22
                        # ansible_ssh_private_key_file: /home/sam/.ssh/id_rsa
                

