---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: True

  tasks:
          - name: add repository for certbot
            apt_repository: 
              repo: deb http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main
              state: present
            when: ansible_distribution_release == 'bionic'
            
          - name: Install base packages
            apt: 
              name: "{{ packages }}"
            vars:
              packages:
                - python-certbot-nginx
                          
          - name: Enable UFW
            ufw:
              state: enabled

          - name: Allow OpenSSH
            ufw:
              rule: allow
              name: OpenSSH

          - name: Allow Nginx Full
            ufw:
              rule: allow
              name: Nginx Full

          - name: Obtain SSL certificate
            command: certbot --nginx -d muokipolls.duckdns.org -d www.muokipolls.duckdns.org
            become: yes
          