---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: True

  tasks:

          - name: Install base packages
            apt: 
              name: "{{ packages }}"
            vars:
              packages:
                # - supervisor
                          
          